package DeckSummary.statictics.cardlibrary;

public enum ValueType {
    NONE, CONSTANT, DAMAGE, BLOCK, MAGIC_NUMBER,
    DAMAGE_TIMES_MAGIC_NUMBER, BLOCK_TIMES_MAGIC_NUMBER,
    DAMAGE_PLUS_MAGIC_NUMBER, BLOCK_PLUS_MAGIC_NUMBER,
    MULTIPLE_OF_DAMAGE, MULTIPLE_OF_BLOCK, MULTIPLE_OF_MAGIC_NUMBER, MULTIPLE_OF_ENERGY,
    ENERGY, ENERGY_TIMES_DAMAGE, ENERGY_TIMES_BLOCK, ENERGY_TIMES_MAGIC_NUMBER
}
